### ISSUE TITLE
Task homebrew_tap finished with error

### ISSUE THREAD

**Issue by impu1se** [mokevnin/dotfiles#14]
I try run "make install_languages.yml" and get message with error :
TASK [homebrew_tap] ***************************************************************************************************
task path: /Users/Serg/dotfiles/install.yml:16
failed: [localhost] (item=homebrew/php) => {"changed": false, "item": "homebrew/php", "msg": "added: 0, unchanged: 0, error: failed to tap: homebrew/php"}
failed: [localhost] (item=homebrew/completions) => {"changed": false, "item": "homebrew/completions", "msg": "added: 0, unchanged: 0, error: failed to tap: homebrew/completions"}

My env: Macbook pro, highSierra, fish.

**Comment by inem** [comment]
https://github.com/Homebrew/homebrew-completions says its deprecated

**Comment by impu1se** [comment]
I installed all from `make install_languages.yml` manual and it work. But i tried run `make nvim_configure i got next message from ansible :
Request failed: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)>
