### ISSUE TITLE
Автоматическое формирование отступов

### ISSUE THREAD

**Issue by rkozlov95** [mokevnin/dotfiles#38]
Есть ли какой-то специальный бинд (комбинация клавиш) с помощью которой можно  автоматически формировать отступы разных размеров (2 пробела или 4 пробела)?  
Сейчас, если я пишу код на php иногда автоматически проставляется отступ в два пробела (для php по стандарту нужно четыре), что не очень удобно.

**Comment by fey** [comment]
Попробуй использовать editorConfig https://editorconfig.org/
