### ISSUE TITLE
module 'nvim-lsp-installer' not found:

### ISSUE THREAD

**Issue by ksbulgakov** [mokevnin/dotfiles#55]
Привет!

Устанавливал сборку и  [вот тут](https://github.com/mokevnin/dotfiles/blob/main/nvim/lua/config.lua#L35) падает ошибка:
E5108: Error executing lua /Users/tino/.config/nvim/lua/config.lua:35: module 'nvim-lsp-installer' not found

Похоже что nvim-lsp-installer нету в области видимости.
Но если код с 35 строки и до конца этого файла перемесить [вот сюда](https://github.com/mokevnin/dotfiles/blob/main/nvim/lua/plugins/lsp.lua#L7) (а вернее не переместить, а вернуть потому как до недавнего времени от там и был) то все едет нормально.

**Comment by mokevnin** [comment]
Код сильно поменялся, подозреваю что сейчас такой ошибки нет
