### ISSUE TITLE
Менеджер плагинов может и vim поставить

### ISSUE THREAD

**Issue by marchukoff** [mokevnin/dotfiles#8]
Подсмотрел идею http://erikzaadi.com/2012/03/19/auto-installing-vundle-from-your-vimrc/
На коленке примерно так:
" Setting up Plug - the minimalist Vim plugin manager
    let iCanHazPlug=1
    let plug_installed=expand('~/.vim/autoload/plug.vim')
    if !filereadable(plug_installed)
        silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
        let iCanHazPlug=0
    endif
 call plug#begin('~/.vim/plugged')
Plug '...здесь подключаем плагины...'

    if iCanHazPlug == 0
        :PlugInstall
    endif

    call plug#end()

**Comment by konofeev** [comment]
Зависимости решения: утилита curl

**Comment by marchukoff** [comment]
Curl или wget может ansible проставить. Автор plug'а и для PowerShell что-то писал. Смысл как бы: vim поставили и пусть дальше он сам заботится о плагинах, чтобы в случае замены скажем plug на vundle не плейбук править, а конфиг vim'а...
